#!/usr/bin/env node
// Generates the stats row as a standalone SVG: Contributions, Current Streak,
// Longest Streak, Repos. Streaks come from the same contribution calendar
// data used by generate-activity.js (readme-aura's `github` object has no
// streak/calendar data, so this hits the GitHub GraphQL API directly).

const QUERY = `
query ($login: String!) {
  user(login: $login) {
    repositories(ownerAffiliations: OWNER, privacy: PUBLIC) {
      totalCount
    }
    contributionsCollection {
      contributionCalendar {
        totalContributions
        weeks {
          contributionDays {
            contributionCount
            date
          }
        }
      }
    }
  }
}`;

async function fetchData(login, token) {
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${token}`,
      'Content-Type': 'application/json',
      'User-Agent': 'readme-generator',
    },
    body: JSON.stringify({ query: QUERY, variables: { login } }),
  });
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
  const json = await res.json();
  if (json.errors) throw new Error(json.errors.map((e) => e.message).join(', '));
  return json.data.user;
}

function computeStreaks(calendar) {
  const days = [];
  for (const week of calendar.weeks) {
    for (const day of week.contributionDays) {
      days.push(day.contributionCount);
    }
  }

  let idx = days.length - 1;
  if (days[idx] === 0) idx--; // today may still be in progress
  let currentStreak = 0;
  while (idx >= 0 && days[idx] > 0) {
    currentStreak++;
    idx--;
  }

  let longestStreak = 0;
  let run = 0;
  for (const count of days) {
    if (count > 0) {
      run++;
      longestStreak = Math.max(longestStreak, run);
    } else {
      run = 0;
    }
  }

  return { currentStreak, longestStreak };
}

function mockData() {
  const weeks = [];
  let total = 0;
  for (let w = 0; w < 53; w++) {
    const days = [];
    for (let d = 0; d < 7; d++) {
      const c = Math.random() < 0.3 ? 0 : Math.floor(Math.random() * 9);
      total += c;
      days.push({ contributionCount: c });
    }
    weeks.push({ contributionDays: days });
  }
  return {
    repositories: { totalCount: 14 },
    contributionsCollection: { contributionCalendar: { totalContributions: total, weeks } },
  };
}

function generateSVG(stats) {
  const W = 860;
  const H = 130;
  const font = `'Inter', -apple-system, 'Segoe UI', sans-serif`;

  const items = [
    { value: stats.totalContributions, label: 'CONTRIBUTIONS', color: '#5ec8f0' },
    { value: stats.currentStreak, label: 'CURRENT STREAK', color: '#ff9ecb' },
    { value: stats.longestStreak, label: 'LONGEST STREAK', color: '#e8c8ff' },
    { value: stats.totalRepos, label: 'REPOS', color: '#7ee7ff' },
  ];

  const colW = W / items.length;
  let cols = '';
  items.forEach((item, i) => {
    const cx = colW * i + colW / 2;
    cols += `<text x="${cx}" y="65" text-anchor="middle" font-family="${font}" font-size="30" font-weight="800" fill="${item.color}">${item.value}</text>`;
    cols += `<text x="${cx}" y="85" text-anchor="middle" font-family="${font}" font-size="11" font-weight="600" fill="rgba(200,195,225,0.45)" letter-spacing="1.5">${item.label}</text>`;
    if (i < items.length - 1) {
      const dx = colW * (i + 1);
      cols += `<line x1="${dx}" y1="35" x2="${dx}" y2="95" stroke="rgba(255,255,255,0.06)" stroke-width="1" />`;
    }
  });

  const starColors = ['#ffffff', '#7ee7ff', '#e8c8ff', '#ff9ecb'];
  const stars = [];
  for (let i = 0; i < 8; i++) {
    stars.push({
      id: 'st-star-' + i,
      cx: Math.round(Math.random() * 820 + 20),
      cy: Math.round(Math.random() * 110 + 10),
      r: (Math.random() * 1.2 + 0.5).toFixed(1),
      dur: (Math.random() * 4 + 3).toFixed(1),
      delay: (Math.random() * 4).toFixed(1),
      color: starColors[i % starColors.length],
    });
  }
  const starTags = stars.map((s) => `<circle id="${s.id}" cx="${s.cx}" cy="${s.cy}" r="${s.r}" fill="${s.color}" />`).join('');
  const starCSS = stars.map((s) => `#${s.id} { animation: twinkle ${s.dur}s ease-in-out infinite; animation-delay: ${s.delay}s; }`).join(' ');

  return `<!-- Generated by scripts/generate-stats.js -->
<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="st-g1" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="rgba(110,20,210,0.5)" />
      <stop offset="70%" stop-color="rgba(110,20,210,0)" />
    </radialGradient>
    <radialGradient id="st-g2" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="rgba(0,140,255,0.35)" />
      <stop offset="70%" stop-color="rgba(0,140,255,0)" />
    </radialGradient>
    <linearGradient id="scg-stats" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="rgba(120,200,255,0)" />
      <stop offset="45%" stop-color="rgba(150,180,255,0.15)" />
      <stop offset="50%" stop-color="rgba(190,150,255,0.5)" />
      <stop offset="55%" stop-color="rgba(150,180,255,0.15)" />
      <stop offset="100%" stop-color="rgba(120,200,255,0)" />
    </linearGradient>
  </defs>
  <style>
    @keyframes twinkle { 0%, 100% { opacity: 0.15; } 50% { opacity: 0.95; } }
    @keyframes scan-move {
      0% { transform: translateX(0px); opacity: 0; }
      10% { opacity: 1; }
      90% { opacity: 1; }
      100% { transform: translateX(1180px); opacity: 0; }
    }
    #scan-stats { animation: scan-move 7s linear infinite; animation-delay: 1.5s; }
    ${starCSS}
  </style>
  <rect x="0.75" y="0.75" width="${W - 1.5}" height="${H - 1.5}" rx="16" fill="#08080c" stroke="rgba(110,80,220,0.18)" stroke-width="1.5" />
  <ellipse cx="120" cy="${H}" rx="220" ry="130" fill="url(#st-g1)" />
  <ellipse cx="${W - 120}" cy="${H}" rx="220" ry="130" fill="url(#st-g2)" />
  ${starTags}
  <rect id="scan-stats" x="-260" y="63" width="260" height="2.5" fill="url(#scg-stats)" />
  ${cols}
</svg>`;
}

(async () => {
  const login = process.env.GITHUB_USER || 'evelynrporto';
  const token = process.env.GITHUB_TOKEN;

  let stats;
  if (token) {
    try {
      const user = await fetchData(login, token);
      const calendar = user.contributionsCollection.contributionCalendar;
      const { currentStreak, longestStreak } = computeStreaks(calendar);
      stats = {
        totalContributions: calendar.totalContributions,
        currentStreak,
        longestStreak,
        totalRepos: user.repositories.totalCount,
      };
    } catch (e) {
      console.error(`generate-stats: ${e.message} — falling back to mock data`);
      const mock = mockData();
      const { currentStreak, longestStreak } = computeStreaks(mock.contributionsCollection.contributionCalendar);
      stats = {
        totalContributions: mock.contributionsCollection.contributionCalendar.totalContributions,
        currentStreak,
        longestStreak,
        totalRepos: mock.repositories.totalCount,
      };
    }
  } else {
    console.log('generate-stats: no GITHUB_TOKEN — using mock data for preview.');
    const mock = mockData();
    const { currentStreak, longestStreak } = computeStreaks(mock.contributionsCollection.contributionCalendar);
    stats = {
      totalContributions: mock.contributionsCollection.contributionCalendar.totalContributions,
      currentStreak,
      longestStreak,
      totalRepos: mock.repositories.totalCount,
    };
  }

  const svg = generateSVG(stats);

  const fs = require('fs');
  const path = require('path');
  const outDir = path.resolve(process.cwd(), '.github/assets');
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'stats.svg');
  fs.writeFileSync(outPath, svg, 'utf-8');
  console.log(`generate-stats: wrote ${outPath}`);
})();
